/***************************************************************************
                          cpu_Funcs.h  -  description
                             -------------------
    begin                : Ñðä Àïð 27 2005
    copyright            : (C) 2005 by vitaly
    email                : vitamin_Caig@mail.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

// defines cpu methods

static void _op_00(CPU* cpu);
static void _op_01(CPU* cpu);
static void _op_02(CPU* cpu);
static void _op_03(CPU* cpu);
static void _op_04(CPU* cpu);
static void _op_05(CPU* cpu);
static void _op_06(CPU* cpu);
static void _op_07(CPU* cpu);
static void _op_08(CPU* cpu);
static void _op_09(CPU* cpu);
static void _op_0A(CPU* cpu);
static void _op_0B(CPU* cpu);
static void _op_0C(CPU* cpu);
static void _op_0D(CPU* cpu);
static void _op_0E(CPU* cpu);
static void _op_0F(CPU* cpu);

static void _op_10(CPU* cpu);
static void _op_11(CPU* cpu);
static void _op_12(CPU* cpu);
static void _op_13(CPU* cpu);
static void _op_14(CPU* cpu);
static void _op_15(CPU* cpu);
static void _op_16(CPU* cpu);
static void _op_17(CPU* cpu);
static void _op_18(CPU* cpu);
static void _op_19(CPU* cpu);
static void _op_1A(CPU* cpu);
static void _op_1B(CPU* cpu);
static void _op_1C(CPU* cpu);
static void _op_1D(CPU* cpu);
static void _op_1E(CPU* cpu);
static void _op_1F(CPU* cpu);

static void _op_20(CPU* cpu);
static void _op_21(CPU* cpu);
static void _op_22(CPU* cpu);
static void _op_23(CPU* cpu);
static void _op_24(CPU* cpu);
static void _op_25(CPU* cpu);
static void _op_26(CPU* cpu);
static void _op_27(CPU* cpu);
static void _op_28(CPU* cpu);
static void _op_29(CPU* cpu);
static void _op_2A(CPU* cpu);
static void _op_2B(CPU* cpu);
static void _op_2C(CPU* cpu);
static void _op_2D(CPU* cpu);
static void _op_2E(CPU* cpu);
static void _op_2F(CPU* cpu);

static void _op_30(CPU* cpu);
static void _op_31(CPU* cpu);
static void _op_32(CPU* cpu);
static void _op_33(CPU* cpu);
static void _op_34(CPU* cpu);
static void _op_35(CPU* cpu);
static void _op_36(CPU* cpu);
static void _op_37(CPU* cpu);
static void _op_38(CPU* cpu);
static void _op_39(CPU* cpu);
static void _op_3A(CPU* cpu);
static void _op_3B(CPU* cpu);
static void _op_3C(CPU* cpu);
static void _op_3D(CPU* cpu);
static void _op_3E(CPU* cpu);
static void _op_3F(CPU* cpu);

// 0x40 == 0x00
static void _op_41(CPU* cpu);
static void _op_42(CPU* cpu);
static void _op_43(CPU* cpu);
static void _op_44(CPU* cpu);
static void _op_45(CPU* cpu);
static void _op_46(CPU* cpu);
static void _op_47(CPU* cpu);
static void _op_48(CPU* cpu);
// 0x49 == 0x00
static void _op_4A(CPU* cpu);
static void _op_4B(CPU* cpu);
static void _op_4C(CPU* cpu);
static void _op_4D(CPU* cpu);
static void _op_4E(CPU* cpu);
static void _op_4F(CPU* cpu);

static void _op_50(CPU* cpu);
static void _op_51(CPU* cpu);
// 0x52 == 0x00
static void _op_53(CPU* cpu);
static void _op_54(CPU* cpu);
static void _op_55(CPU* cpu);
static void _op_56(CPU* cpu);
static void _op_57(CPU* cpu);
static void _op_58(CPU* cpu);
static void _op_59(CPU* cpu);
static void _op_5A(CPU* cpu);
// 0x5b == 0x00
static void _op_5C(CPU* cpu);
static void _op_5D(CPU* cpu);
static void _op_5E(CPU* cpu);
static void _op_5F(CPU* cpu);

static void _op_60(CPU* cpu);
static void _op_61(CPU* cpu);
static void _op_62(CPU* cpu);
static void _op_63(CPU* cpu);
// 0x64 == 0x00
static void _op_65(CPU* cpu);
static void _op_66(CPU* cpu);
static void _op_67(CPU* cpu);
static void _op_68(CPU* cpu);
static void _op_69(CPU* cpu);
static void _op_6A(CPU* cpu);
static void _op_6B(CPU* cpu);
static void _op_6C(CPU* cpu);
// 0x6d == 0x00
static void _op_6E(CPU* cpu);
static void _op_6F(CPU* cpu);

static void _op_70(CPU* cpu);
static void _op_71(CPU* cpu);
static void _op_72(CPU* cpu);
static void _op_73(CPU* cpu);
static void _op_74(CPU* cpu);
static void _op_75(CPU* cpu);
static void _op_76(CPU* cpu);
static void _op_77(CPU* cpu);
static void _op_78(CPU* cpu);
static void _op_79(CPU* cpu);
static void _op_7A(CPU* cpu);
static void _op_7B(CPU* cpu);
static void _op_7C(CPU* cpu);
static void _op_7D(CPU* cpu);
static void _op_7E(CPU* cpu);
// 0x7f == 0x00

static void _op_80(CPU* cpu);
static void _op_81(CPU* cpu);
static void _op_82(CPU* cpu);
static void _op_83(CPU* cpu);
static void _op_84(CPU* cpu);
static void _op_85(CPU* cpu);
static void _op_86(CPU* cpu);
static void _op_87(CPU* cpu);
static void _op_88(CPU* cpu);
static void _op_89(CPU* cpu);
static void _op_8A(CPU* cpu);
static void _op_8B(CPU* cpu);
static void _op_8C(CPU* cpu);
static void _op_8D(CPU* cpu);
static void _op_8E(CPU* cpu);
static void _op_8F(CPU* cpu);

static void _op_90(CPU* cpu);
static void _op_91(CPU* cpu);
static void _op_92(CPU* cpu);
static void _op_93(CPU* cpu);
static void _op_94(CPU* cpu);
static void _op_95(CPU* cpu);
static void _op_96(CPU* cpu);
static void _op_97(CPU* cpu);
static void _op_98(CPU* cpu);
static void _op_99(CPU* cpu);
static void _op_9A(CPU* cpu);
static void _op_9B(CPU* cpu);
static void _op_9C(CPU* cpu);
static void _op_9D(CPU* cpu);
static void _op_9E(CPU* cpu);
static void _op_9F(CPU* cpu);

static void _op_A0(CPU* cpu);
static void _op_A1(CPU* cpu);
static void _op_A2(CPU* cpu);
static void _op_A3(CPU* cpu);
static void _op_A4(CPU* cpu);
static void _op_A5(CPU* cpu);
static void _op_A6(CPU* cpu);
static void _op_A7(CPU* cpu);
static void _op_A8(CPU* cpu);
static void _op_A9(CPU* cpu);
static void _op_AA(CPU* cpu);
static void _op_AB(CPU* cpu);
static void _op_AC(CPU* cpu);
static void _op_AD(CPU* cpu);
static void _op_AE(CPU* cpu);
static void _op_AF(CPU* cpu);

static void _op_B0(CPU* cpu);
static void _op_B1(CPU* cpu);
static void _op_B2(CPU* cpu);
static void _op_B3(CPU* cpu);
static void _op_B4(CPU* cpu);
static void _op_B5(CPU* cpu);
static void _op_B6(CPU* cpu);
static void _op_B7(CPU* cpu);
static void _op_B8(CPU* cpu);
static void _op_B9(CPU* cpu);
static void _op_BA(CPU* cpu);
static void _op_BB(CPU* cpu);
static void _op_BC(CPU* cpu);
static void _op_BD(CPU* cpu);
static void _op_BE(CPU* cpu);
static void _op_BF(CPU* cpu);

static void _op_C0(CPU* cpu);
static void _op_C1(CPU* cpu);
static void _op_C2(CPU* cpu);
static void _op_C3(CPU* cpu);
static void _op_C4(CPU* cpu);
static void _op_C5(CPU* cpu);
static void _op_C6(CPU* cpu);
static void _op_C7(CPU* cpu);
static void _op_C8(CPU* cpu);
static void _op_C9(CPU* cpu);
static void _op_CA(CPU* cpu);
static void _op_CB(CPU* cpu);
static void _op_CC(CPU* cpu);
static void _op_CD(CPU* cpu);
static void _op_CE(CPU* cpu);
static void _op_CF(CPU* cpu);

static void _op_D0(CPU* cpu);
static void _op_D1(CPU* cpu);
static void _op_D2(CPU* cpu);
static void _op_D3(CPU* cpu);
static void _op_D4(CPU* cpu);
static void _op_D5(CPU* cpu);
static void _op_D6(CPU* cpu);
static void _op_D7(CPU* cpu);
static void _op_D8(CPU* cpu);
static void _op_D9(CPU* cpu);
static void _op_DA(CPU* cpu);
static void _op_DB(CPU* cpu);
static void _op_DC(CPU* cpu);
static void _op_DD(CPU* cpu);
static void _op_DE(CPU* cpu);
static void _op_DF(CPU* cpu);

static void _op_E0(CPU* cpu);
static void _op_E1(CPU* cpu);
static void _op_E2(CPU* cpu);
static void _op_E3(CPU* cpu);
static void _op_E4(CPU* cpu);
static void _op_E5(CPU* cpu);
static void _op_E6(CPU* cpu);
static void _op_E7(CPU* cpu);
static void _op_E8(CPU* cpu);
static void _op_E9(CPU* cpu);
static void _op_EA(CPU* cpu);
static void _op_EB(CPU* cpu);
static void _op_EC(CPU* cpu);
static void _op_ED(CPU* cpu);
static void _op_EE(CPU* cpu);
static void _op_EF(CPU* cpu);

static void _op_F0(CPU* cpu);
static void _op_F1(CPU* cpu);
static void _op_F2(CPU* cpu);
static void _op_F3(CPU* cpu);
static void _op_F4(CPU* cpu);
static void _op_F5(CPU* cpu);
static void _op_F6(CPU* cpu);
static void _op_F7(CPU* cpu);
static void _op_F8(CPU* cpu);
static void _op_F9(CPU* cpu);
static void _op_FA(CPU* cpu);
static void _op_FB(CPU* cpu);
static void _op_FC(CPU* cpu);
static void _op_FD(CPU* cpu);
static void _op_FE(CPU* cpu);
static void _op_FF(CPU* cpu);

// CB operations
static void _opCB_00(CPU* cpu);
static void _opCB_01(CPU* cpu);
static void _opCB_02(CPU* cpu);
static void _opCB_03(CPU* cpu);
static void _opCB_04(CPU* cpu);
static void _opCB_05(CPU* cpu);
static void _opCB_06(CPU* cpu);
static void _opCB_07(CPU* cpu);
static void _opCB_08(CPU* cpu);
static void _opCB_09(CPU* cpu);
static void _opCB_0A(CPU* cpu);
static void _opCB_0B(CPU* cpu);
static void _opCB_0C(CPU* cpu);
static void _opCB_0D(CPU* cpu);
static void _opCB_0E(CPU* cpu);
static void _opCB_0F(CPU* cpu);

static void _opCB_10(CPU* cpu);
static void _opCB_11(CPU* cpu);
static void _opCB_12(CPU* cpu);
static void _opCB_13(CPU* cpu);
static void _opCB_14(CPU* cpu);
static void _opCB_15(CPU* cpu);
static void _opCB_16(CPU* cpu);
static void _opCB_17(CPU* cpu);
static void _opCB_18(CPU* cpu);
static void _opCB_19(CPU* cpu);
static void _opCB_1A(CPU* cpu);
static void _opCB_1B(CPU* cpu);
static void _opCB_1C(CPU* cpu);
static void _opCB_1D(CPU* cpu);
static void _opCB_1E(CPU* cpu);
static void _opCB_1F(CPU* cpu);

static void _opCB_20(CPU* cpu);
static void _opCB_21(CPU* cpu);
static void _opCB_22(CPU* cpu);
static void _opCB_23(CPU* cpu);
static void _opCB_24(CPU* cpu);
static void _opCB_25(CPU* cpu);
static void _opCB_26(CPU* cpu);
static void _opCB_27(CPU* cpu);
static void _opCB_28(CPU* cpu);
static void _opCB_29(CPU* cpu);
static void _opCB_2A(CPU* cpu);
static void _opCB_2B(CPU* cpu);
static void _opCB_2C(CPU* cpu);
static void _opCB_2D(CPU* cpu);
static void _opCB_2E(CPU* cpu);
static void _opCB_2F(CPU* cpu);

static void _opCB_30(CPU* cpu);
static void _opCB_31(CPU* cpu);
static void _opCB_32(CPU* cpu);
static void _opCB_33(CPU* cpu);
static void _opCB_34(CPU* cpu);
static void _opCB_35(CPU* cpu);
static void _opCB_36(CPU* cpu);
static void _opCB_37(CPU* cpu);
static void _opCB_38(CPU* cpu);
static void _opCB_39(CPU* cpu);
static void _opCB_3A(CPU* cpu);
static void _opCB_3B(CPU* cpu);
static void _opCB_3C(CPU* cpu);
static void _opCB_3D(CPU* cpu);
static void _opCB_3E(CPU* cpu);
static void _opCB_3F(CPU* cpu);

static void _opCB_40(CPU* cpu);
static void _opCB_41(CPU* cpu);
static void _opCB_42(CPU* cpu);
static void _opCB_43(CPU* cpu);
static void _opCB_44(CPU* cpu);
static void _opCB_45(CPU* cpu);
static void _opCB_46(CPU* cpu);
static void _opCB_47(CPU* cpu);
static void _opCB_48(CPU* cpu);
static void _opCB_49(CPU* cpu);
static void _opCB_4A(CPU* cpu);
static void _opCB_4B(CPU* cpu);
static void _opCB_4C(CPU* cpu);
static void _opCB_4D(CPU* cpu);
static void _opCB_4E(CPU* cpu);
static void _opCB_4F(CPU* cpu);

static void _opCB_50(CPU* cpu);
static void _opCB_51(CPU* cpu);
static void _opCB_52(CPU* cpu);
static void _opCB_53(CPU* cpu);
static void _opCB_54(CPU* cpu);
static void _opCB_55(CPU* cpu);
static void _opCB_56(CPU* cpu);
static void _opCB_57(CPU* cpu);
static void _opCB_58(CPU* cpu);
static void _opCB_59(CPU* cpu);
static void _opCB_5A(CPU* cpu);
static void _opCB_5B(CPU* cpu);
static void _opCB_5C(CPU* cpu);
static void _opCB_5D(CPU* cpu);
static void _opCB_5E(CPU* cpu);
static void _opCB_5F(CPU* cpu);

static void _opCB_60(CPU* cpu);
static void _opCB_61(CPU* cpu);
static void _opCB_62(CPU* cpu);
static void _opCB_63(CPU* cpu);
static void _opCB_64(CPU* cpu);
static void _opCB_65(CPU* cpu);
static void _opCB_66(CPU* cpu);
static void _opCB_67(CPU* cpu);
static void _opCB_68(CPU* cpu);
static void _opCB_69(CPU* cpu);
static void _opCB_6A(CPU* cpu);
static void _opCB_6B(CPU* cpu);
static void _opCB_6C(CPU* cpu);
static void _opCB_6D(CPU* cpu);
static void _opCB_6E(CPU* cpu);
static void _opCB_6F(CPU* cpu);

static void _opCB_70(CPU* cpu);
static void _opCB_71(CPU* cpu);
static void _opCB_72(CPU* cpu);
static void _opCB_73(CPU* cpu);
static void _opCB_74(CPU* cpu);
static void _opCB_75(CPU* cpu);
static void _opCB_76(CPU* cpu);
static void _opCB_77(CPU* cpu);
static void _opCB_78(CPU* cpu);
static void _opCB_79(CPU* cpu);
static void _opCB_7A(CPU* cpu);
static void _opCB_7B(CPU* cpu);
static void _opCB_7C(CPU* cpu);
static void _opCB_7D(CPU* cpu);
static void _opCB_7E(CPU* cpu);
static void _opCB_7F(CPU* cpu);

static void _opCB_80(CPU* cpu);
static void _opCB_81(CPU* cpu);
static void _opCB_82(CPU* cpu);
static void _opCB_83(CPU* cpu);
static void _opCB_84(CPU* cpu);
static void _opCB_85(CPU* cpu);
static void _opCB_86(CPU* cpu);
static void _opCB_87(CPU* cpu);
static void _opCB_88(CPU* cpu);
static void _opCB_89(CPU* cpu);
static void _opCB_8A(CPU* cpu);
static void _opCB_8B(CPU* cpu);
static void _opCB_8C(CPU* cpu);
static void _opCB_8D(CPU* cpu);
static void _opCB_8E(CPU* cpu);
static void _opCB_8F(CPU* cpu);

static void _opCB_90(CPU* cpu);
static void _opCB_91(CPU* cpu);
static void _opCB_92(CPU* cpu);
static void _opCB_93(CPU* cpu);
static void _opCB_94(CPU* cpu);
static void _opCB_95(CPU* cpu);
static void _opCB_96(CPU* cpu);
static void _opCB_97(CPU* cpu);
static void _opCB_98(CPU* cpu);
static void _opCB_99(CPU* cpu);
static void _opCB_9A(CPU* cpu);
static void _opCB_9B(CPU* cpu);
static void _opCB_9C(CPU* cpu);
static void _opCB_9D(CPU* cpu);
static void _opCB_9E(CPU* cpu);
static void _opCB_9F(CPU* cpu);

static void _opCB_A0(CPU* cpu);
static void _opCB_A1(CPU* cpu);
static void _opCB_A2(CPU* cpu);
static void _opCB_A3(CPU* cpu);
static void _opCB_A4(CPU* cpu);
static void _opCB_A5(CPU* cpu);
static void _opCB_A6(CPU* cpu);
static void _opCB_A7(CPU* cpu);
static void _opCB_A8(CPU* cpu);
static void _opCB_A9(CPU* cpu);
static void _opCB_AA(CPU* cpu);
static void _opCB_AB(CPU* cpu);
static void _opCB_AC(CPU* cpu);
static void _opCB_AD(CPU* cpu);
static void _opCB_AE(CPU* cpu);
static void _opCB_AF(CPU* cpu);

static void _opCB_B0(CPU* cpu);
static void _opCB_B1(CPU* cpu);
static void _opCB_B2(CPU* cpu);
static void _opCB_B3(CPU* cpu);
static void _opCB_B4(CPU* cpu);
static void _opCB_B5(CPU* cpu);
static void _opCB_B6(CPU* cpu);
static void _opCB_B7(CPU* cpu);
static void _opCB_B8(CPU* cpu);
static void _opCB_B9(CPU* cpu);
static void _opCB_BA(CPU* cpu);
static void _opCB_BB(CPU* cpu);
static void _opCB_BC(CPU* cpu);
static void _opCB_BD(CPU* cpu);
static void _opCB_BE(CPU* cpu);
static void _opCB_BF(CPU* cpu);

static void _opCB_C0(CPU* cpu);
static void _opCB_C1(CPU* cpu);
static void _opCB_C2(CPU* cpu);
static void _opCB_C3(CPU* cpu);
static void _opCB_C4(CPU* cpu);
static void _opCB_C5(CPU* cpu);
static void _opCB_C6(CPU* cpu);
static void _opCB_C7(CPU* cpu);
static void _opCB_C8(CPU* cpu);
static void _opCB_C9(CPU* cpu);
static void _opCB_CA(CPU* cpu);
static void _opCB_CB(CPU* cpu);
static void _opCB_CC(CPU* cpu);
static void _opCB_CD(CPU* cpu);
static void _opCB_CE(CPU* cpu);
static void _opCB_CF(CPU* cpu);

static void _opCB_D0(CPU* cpu);
static void _opCB_D1(CPU* cpu);
static void _opCB_D2(CPU* cpu);
static void _opCB_D3(CPU* cpu);
static void _opCB_D4(CPU* cpu);
static void _opCB_D5(CPU* cpu);
static void _opCB_D6(CPU* cpu);
static void _opCB_D7(CPU* cpu);
static void _opCB_D8(CPU* cpu);
static void _opCB_D9(CPU* cpu);
static void _opCB_DA(CPU* cpu);
static void _opCB_DB(CPU* cpu);
static void _opCB_DC(CPU* cpu);
static void _opCB_DD(CPU* cpu);
static void _opCB_DE(CPU* cpu);
static void _opCB_DF(CPU* cpu);

static void _opCB_E0(CPU* cpu);
static void _opCB_E1(CPU* cpu);
static void _opCB_E2(CPU* cpu);
static void _opCB_E3(CPU* cpu);
static void _opCB_E4(CPU* cpu);
static void _opCB_E5(CPU* cpu);
static void _opCB_E6(CPU* cpu);
static void _opCB_E7(CPU* cpu);
static void _opCB_E8(CPU* cpu);
static void _opCB_E9(CPU* cpu);
static void _opCB_EA(CPU* cpu);
static void _opCB_EB(CPU* cpu);
static void _opCB_EC(CPU* cpu);
static void _opCB_ED(CPU* cpu);
static void _opCB_EE(CPU* cpu);
static void _opCB_EF(CPU* cpu);

static void _opCB_F0(CPU* cpu);
static void _opCB_F1(CPU* cpu);
static void _opCB_F2(CPU* cpu);
static void _opCB_F3(CPU* cpu);
static void _opCB_F4(CPU* cpu);
static void _opCB_F5(CPU* cpu);
static void _opCB_F6(CPU* cpu);
static void _opCB_F7(CPU* cpu);
static void _opCB_F8(CPU* cpu);
static void _opCB_F9(CPU* cpu);
static void _opCB_FA(CPU* cpu);
static void _opCB_FB(CPU* cpu);
static void _opCB_FC(CPU* cpu);
static void _opCB_FD(CPU* cpu);
static void _opCB_FE(CPU* cpu);
static void _opCB_FF(CPU* cpu);


static void _opED_40(CPU* cpu);
static void _opED_41(CPU* cpu);
static void _opED_42(CPU* cpu);
static void _opED_43(CPU* cpu);
static void _opED_44(CPU* cpu);
static void _opED_45(CPU* cpu);
static void _opED_46(CPU* cpu);
static void _opED_47(CPU* cpu);
static void _opED_48(CPU* cpu);
static void _opED_49(CPU* cpu);
static void _opED_4A(CPU* cpu);
static void _opED_4B(CPU* cpu);
static void _opED_4C(CPU* cpu);
static void _opED_4D(CPU* cpu);
static void _opED_4E(CPU* cpu);
static void _opED_4F(CPU* cpu);

static void _opED_50(CPU* cpu);
static void _opED_51(CPU* cpu);
static void _opED_52(CPU* cpu);
static void _opED_53(CPU* cpu);
static void _opED_54(CPU* cpu);
static void _opED_55(CPU* cpu);
static void _opED_56(CPU* cpu);
static void _opED_57(CPU* cpu);
static void _opED_58(CPU* cpu);
static void _opED_59(CPU* cpu);
static void _opED_5A(CPU* cpu);
static void _opED_5B(CPU* cpu);
static void _opED_5C(CPU* cpu);
static void _opED_5D(CPU* cpu);
static void _opED_5E(CPU* cpu);
static void _opED_5F(CPU* cpu);

static void _opED_60(CPU* cpu);
static void _opED_61(CPU* cpu);
static void _opED_62(CPU* cpu);
static void _opED_63(CPU* cpu);
static void _opED_64(CPU* cpu);
static void _opED_65(CPU* cpu);
static void _opED_66(CPU* cpu);
static void _opED_67(CPU* cpu);
static void _opED_68(CPU* cpu);
static void _opED_69(CPU* cpu);
static void _opED_6A(CPU* cpu);
static void _opED_6B(CPU* cpu);
static void _opED_6C(CPU* cpu);
static void _opED_6D(CPU* cpu);
static void _opED_6E(CPU* cpu);
static void _opED_6F(CPU* cpu);

static void _opED_70(CPU* cpu);
static void _opED_71(CPU* cpu);
static void _opED_72(CPU* cpu);
static void _opED_73(CPU* cpu);
static void _opED_74(CPU* cpu);
static void _opED_75(CPU* cpu);
static void _opED_76(CPU* cpu);
static void _opED_77(CPU* cpu);
static void _opED_78(CPU* cpu);
static void _opED_79(CPU* cpu);
static void _opED_7A(CPU* cpu);
static void _opED_7B(CPU* cpu);
static void _opED_7C(CPU* cpu);
static void _opED_7D(CPU* cpu);
static void _opED_7E(CPU* cpu);
static void _opED_7F(CPU* cpu);

static void _opED_A0(CPU* cpu);
static void _opED_A1(CPU* cpu);
static void _opED_A2(CPU* cpu);
static void _opED_A3(CPU* cpu);
static void _opED_A4(CPU* cpu);
static void _opED_A5(CPU* cpu);
static void _opED_A6(CPU* cpu);
static void _opED_A7(CPU* cpu);
static void _opED_A8(CPU* cpu);
static void _opED_A9(CPU* cpu);
static void _opED_AA(CPU* cpu);
static void _opED_AB(CPU* cpu);
static void _opED_AC(CPU* cpu);
static void _opED_AD(CPU* cpu);
static void _opED_AE(CPU* cpu);
static void _opED_AF(CPU* cpu);

static void _opED_B0(CPU* cpu);
static void _opED_B1(CPU* cpu);
static void _opED_B2(CPU* cpu);
static void _opED_B3(CPU* cpu);
static void _opED_B4(CPU* cpu);
static void _opED_B5(CPU* cpu);
static void _opED_B6(CPU* cpu);
static void _opED_B7(CPU* cpu);
static void _opED_B8(CPU* cpu);
static void _opED_B9(CPU* cpu);
static void _opED_BA(CPU* cpu);
static void _opED_BB(CPU* cpu);
static void _opED_BC(CPU* cpu);
static void _opED_BD(CPU* cpu);
static void _opED_BE(CPU* cpu);
static void _opED_BF(CPU* cpu);

static void _opDD_09(CPU* cpu);
static void _opDD_19(CPU* cpu);
static void _opDD_21(CPU* cpu);
static void _opDD_22(CPU* cpu);
static void _opDD_23(CPU* cpu);
static void _opDD_24(CPU* cpu);
static void _opDD_25(CPU* cpu);
static void _opDD_26(CPU* cpu);
static void _opDD_29(CPU* cpu);
static void _opDD_2A(CPU* cpu);
static void _opDD_2B(CPU* cpu);
static void _opDD_2C(CPU* cpu);
static void _opDD_2D(CPU* cpu);
static void _opDD_2E(CPU* cpu);
static void _opDD_34(CPU* cpu);
static void _opDD_35(CPU* cpu);
static void _opDD_36(CPU* cpu);
static void _opDD_39(CPU* cpu);
static void _opDD_44(CPU* cpu);
static void _opDD_45(CPU* cpu);
static void _opDD_46(CPU* cpu);
static void _opDD_47(CPU* cpu);
static void _opDD_4B(CPU* cpu);
static void _opDD_4C(CPU* cpu);
static void _opDD_4D(CPU* cpu);
static void _opDD_4E(CPU* cpu);
static void _opDD_4F(CPU* cpu);
static void _opDD_54(CPU* cpu);
static void _opDD_55(CPU* cpu);
static void _opDD_56(CPU* cpu);
static void _opDD_57(CPU* cpu);
static void _opDD_5B(CPU* cpu);
static void _opDD_5C(CPU* cpu);
static void _opDD_5D(CPU* cpu);
static void _opDD_5E(CPU* cpu);
static void _opDD_5F(CPU* cpu);
static void _opDD_60(CPU* cpu);
static void _opDD_61(CPU* cpu);
static void _opDD_62(CPU* cpu);
static void _opDD_63(CPU* cpu);
static void _opDD_65(CPU* cpu);
static void _opDD_66(CPU* cpu);
static void _opDD_67(CPU* cpu);
static void _opDD_68(CPU* cpu);
static void _opDD_69(CPU* cpu);
static void _opDD_6A(CPU* cpu);
static void _opDD_6B(CPU* cpu);
static void _opDD_6C(CPU* cpu);
static void _opDD_6E(CPU* cpu);
static void _opDD_6F(CPU* cpu);
static void _opDD_70(CPU* cpu);
static void _opDD_71(CPU* cpu);
static void _opDD_72(CPU* cpu);
static void _opDD_73(CPU* cpu);
static void _opDD_74(CPU* cpu);
static void _opDD_75(CPU* cpu);
static void _opDD_77(CPU* cpu);
static void _opDD_7C(CPU* cpu);
static void _opDD_7D(CPU* cpu);
static void _opDD_7E(CPU* cpu);
static void _opDD_84(CPU* cpu);
static void _opDD_85(CPU* cpu);
static void _opDD_86(CPU* cpu);
static void _opDD_8C(CPU* cpu);
static void _opDD_8D(CPU* cpu);
static void _opDD_8E(CPU* cpu);
static void _opDD_94(CPU* cpu);
static void _opDD_95(CPU* cpu);
static void _opDD_96(CPU* cpu);
static void _opDD_9C(CPU* cpu);
static void _opDD_9D(CPU* cpu);
static void _opDD_9E(CPU* cpu);
static void _opDD_A4(CPU* cpu);
static void _opDD_A5(CPU* cpu);
static void _opDD_A6(CPU* cpu);
static void _opDD_AC(CPU* cpu);
static void _opDD_AD(CPU* cpu);
static void _opDD_AE(CPU* cpu);
static void _opDD_B4(CPU* cpu);
static void _opDD_B5(CPU* cpu);
static void _opDD_B6(CPU* cpu);
static void _opDD_BC(CPU* cpu);
static void _opDD_BD(CPU* cpu);
static void _opDD_BE(CPU* cpu);
static void _opDD_E1(CPU* cpu);
static void _opDD_E3(CPU* cpu);
static void _opDD_E5(CPU* cpu);
static void _opDD_E9(CPU* cpu);
static void _opDD_EC(CPU* cpu);
static void _opDD_ED(CPU* cpu);
static void _opDD_EE(CPU* cpu);
static void _opDD_EF(CPU* cpu);
static void _opDD_F9(CPU* cpu);

static void _opFD_09(CPU* cpu);
static void _opFD_19(CPU* cpu);
static void _opFD_21(CPU* cpu);
static void _opFD_22(CPU* cpu);
static void _opFD_23(CPU* cpu);
static void _opFD_24(CPU* cpu);
static void _opFD_25(CPU* cpu);
static void _opFD_26(CPU* cpu);
static void _opFD_29(CPU* cpu);
static void _opFD_2A(CPU* cpu);
static void _opFD_2B(CPU* cpu);
static void _opFD_2C(CPU* cpu);
static void _opFD_2D(CPU* cpu);
static void _opFD_2E(CPU* cpu);
static void _opFD_34(CPU* cpu);
static void _opFD_35(CPU* cpu);
static void _opFD_36(CPU* cpu);
static void _opFD_39(CPU* cpu);
static void _opFD_44(CPU* cpu);
static void _opFD_45(CPU* cpu);
static void _opFD_46(CPU* cpu);
static void _opFD_47(CPU* cpu);
static void _opFD_4B(CPU* cpu);
static void _opFD_4C(CPU* cpu);
static void _opFD_4D(CPU* cpu);
static void _opFD_4E(CPU* cpu);
static void _opFD_4F(CPU* cpu);
static void _opFD_54(CPU* cpu);
static void _opFD_55(CPU* cpu);
static void _opFD_56(CPU* cpu);
static void _opFD_57(CPU* cpu);
static void _opFD_5B(CPU* cpu);
static void _opFD_5C(CPU* cpu);
static void _opFD_5D(CPU* cpu);
static void _opFD_5E(CPU* cpu);
static void _opFD_5F(CPU* cpu);
static void _opFD_60(CPU* cpu);
static void _opFD_61(CPU* cpu);
static void _opFD_62(CPU* cpu);
static void _opFD_63(CPU* cpu);
static void _opFD_65(CPU* cpu);
static void _opFD_66(CPU* cpu);
static void _opFD_67(CPU* cpu);
static void _opFD_68(CPU* cpu);
static void _opFD_69(CPU* cpu);
static void _opFD_6A(CPU* cpu);
static void _opFD_6B(CPU* cpu);
static void _opFD_6C(CPU* cpu);
static void _opFD_6E(CPU* cpu);
static void _opFD_6F(CPU* cpu);
static void _opFD_70(CPU* cpu);
static void _opFD_71(CPU* cpu);
static void _opFD_72(CPU* cpu);
static void _opFD_73(CPU* cpu);
static void _opFD_74(CPU* cpu);
static void _opFD_75(CPU* cpu);
static void _opFD_77(CPU* cpu);
static void _opFD_7C(CPU* cpu);
static void _opFD_7D(CPU* cpu);
static void _opFD_7E(CPU* cpu);
static void _opFD_84(CPU* cpu);
static void _opFD_85(CPU* cpu);
static void _opFD_86(CPU* cpu);
static void _opFD_8C(CPU* cpu);
static void _opFD_8D(CPU* cpu);
static void _opFD_8E(CPU* cpu);
static void _opFD_94(CPU* cpu);
static void _opFD_95(CPU* cpu);
static void _opFD_96(CPU* cpu);
static void _opFD_9C(CPU* cpu);
static void _opFD_9D(CPU* cpu);
static void _opFD_9E(CPU* cpu);
static void _opFD_A4(CPU* cpu);
static void _opFD_A5(CPU* cpu);
static void _opFD_A6(CPU* cpu);
static void _opFD_AC(CPU* cpu);
static void _opFD_AD(CPU* cpu);
static void _opFD_AE(CPU* cpu);
static void _opFD_B4(CPU* cpu);
static void _opFD_B5(CPU* cpu);
static void _opFD_B6(CPU* cpu);
static void _opFD_BC(CPU* cpu);
static void _opFD_BD(CPU* cpu);
static void _opFD_BE(CPU* cpu);
static void _opFD_E1(CPU* cpu);
static void _opFD_E3(CPU* cpu);
static void _opFD_E5(CPU* cpu);
static void _opFD_E9(CPU* cpu);
static void _opFD_EC(CPU* cpu);
static void _opFD_ED(CPU* cpu);
static void _opFD_EE(CPU* cpu);
static void _opFD_EF(CPU* cpu);
static void _opFD_F9(CPU* cpu);

static BYTE _oplx_00(CPU* cpu, BYTE byte);
static BYTE _oplx_08(CPU* cpu, BYTE byte);
static BYTE _oplx_10(CPU* cpu, BYTE byte);
static BYTE _oplx_18(CPU* cpu, BYTE byte);
static BYTE _oplx_20(CPU* cpu, BYTE byte);
static BYTE _oplx_28(CPU* cpu, BYTE byte);
static BYTE _oplx_30(CPU* cpu, BYTE byte);
static BYTE _oplx_38(CPU* cpu, BYTE byte);
static BYTE _oplx_40(CPU* cpu, BYTE byte);
static BYTE _oplx_48(CPU* cpu, BYTE byte);
static BYTE _oplx_50(CPU* cpu, BYTE byte);
static BYTE _oplx_58(CPU* cpu, BYTE byte);
static BYTE _oplx_60(CPU* cpu, BYTE byte);
static BYTE _oplx_68(CPU* cpu, BYTE byte);
static BYTE _oplx_70(CPU* cpu, BYTE byte);
static BYTE _oplx_78(CPU* cpu, BYTE byte);
static BYTE _oplx_80(CPU* cpu, BYTE byte);
static BYTE _oplx_88(CPU* cpu, BYTE byte);
static BYTE _oplx_90(CPU* cpu, BYTE byte);
static BYTE _oplx_98(CPU* cpu, BYTE byte);
static BYTE _oplx_A0(CPU* cpu, BYTE byte);
static BYTE _oplx_A8(CPU* cpu, BYTE byte);
static BYTE _oplx_B0(CPU* cpu, BYTE byte);
static BYTE _oplx_B8(CPU* cpu, BYTE byte);
static BYTE _oplx_C0(CPU* cpu, BYTE byte);
static BYTE _oplx_C8(CPU* cpu, BYTE byte);
static BYTE _oplx_D0(CPU* cpu, BYTE byte);
static BYTE _oplx_D8(CPU* cpu, BYTE byte);
static BYTE _oplx_E0(CPU* cpu, BYTE byte);
static BYTE _oplx_E8(CPU* cpu, BYTE byte);
static BYTE _oplx_F0(CPU* cpu, BYTE byte);
static BYTE _oplx_F8(CPU* cpu, BYTE byte);

static void _opDDFD(CPU* cpu, BYTE opcode);

//extended functions
static void _opExtCaps(CPU* pCPU);
static void _opExtIntTicks(CPU* pCPU);
static void _opExtTotalTicks(CPU* pCPU);
static void _opExtBreakpoint(CPU* pCPU);
